<?php

namespace Sequenzy\Widgets\Requests;

use Sequenzy\Core\Json\JsonSerializableType;
use Sequenzy\Widgets\Types\SubmitSignupFormRequestDuplicateStrategy;
use Sequenzy\Core\Json\JsonProperty;
use Sequenzy\Core\Types\ArrayType;

class SubmitSignupFormRequest extends JsonSerializableType
{
    /**
     * @var ?value-of<SubmitSignupFormRequestDuplicateStrategy> $duplicateStrategy How to handle an existing contact with the submitted email. Use skip to preserve fields, merge to fill missing fields, or overwrite to replace submitted fields. Merge and overwrite require duplicateStrategyToken from the form builder.
     */
    public ?string $duplicateStrategy;

    /**
     * @var ?string $duplicateStrategyToken Signed token generated by the form builder for the selected duplicateStrategy. Required for merge or overwrite.
     */
    public ?string $duplicateStrategyToken;

    /**
     * @var ?string $lists Comma-separated list IDs. Omit for workspace default lists, or provide an empty value for no lists.
     */
    public ?string $lists;

    /**
     * @var ?string $tags Comma-separated tag IDs to apply to the subscriber.
     */
    public ?string $tags;

    /**
     * @var ?array<string, mixed> $customAttributes Subscriber custom attributes
     */
    #[JsonProperty('customAttributes'), ArrayType(['string' => 'mixed'])]
    public ?array $customAttributes;

    /**
     * @var ?value-of<SubmitSignupFormRequestDuplicateStrategy> $bodyDuplicateStrategy Body alternative to the duplicateStrategy query parameter. Query parameter takes precedence. Merge and overwrite require duplicateStrategyToken.
     */
    #[JsonProperty('duplicateStrategy')]
    public ?string $bodyDuplicateStrategy;

    /**
     * @var ?string $bodyDuplicateStrategyToken Body alternative to the duplicateStrategyToken query parameter.
     */
    #[JsonProperty('duplicateStrategyToken')]
    public ?string $bodyDuplicateStrategyToken;

    /**
     * @var string $email Subscriber email address
     */
    #[JsonProperty('email')]
    public string $email;

    /**
     * @var ?string $firstName
     */
    #[JsonProperty('firstName')]
    public ?string $firstName;

    /**
     * @var ?string $lastName
     */
    #[JsonProperty('lastName')]
    public ?string $lastName;

    /**
     * @var ?array<string> $listIds
     */
    #[JsonProperty('listIds'), ArrayType(['string'])]
    public ?array $listIds;

    /**
     * @var ?string $phone Subscriber phone number in E.164 or US national format. Stored on the base subscriber profile and does not grant SMS consent.
     */
    #[JsonProperty('phone')]
    public ?string $phone;

    /**
     * @var ?string $redirectUrl Http(s) URL or bare domain to redirect to after successful submission
     */
    #[JsonProperty('redirectUrl')]
    public ?string $redirectUrl;

    /**
     * @var ?array<string> $tagIds Existing tag IDs to apply to the subscriber
     */
    #[JsonProperty('tagIds'), ArrayType(['string'])]
    public ?array $tagIds;

    /**
     * @var ?string $website Honeypot field. Leave empty.
     */
    #[JsonProperty('website')]
    public ?string $website;

    /**
     * @param array{
     *   email: string,
     *   duplicateStrategy?: ?value-of<SubmitSignupFormRequestDuplicateStrategy>,
     *   duplicateStrategyToken?: ?string,
     *   lists?: ?string,
     *   tags?: ?string,
     *   customAttributes?: ?array<string, mixed>,
     *   bodyDuplicateStrategy?: ?value-of<SubmitSignupFormRequestDuplicateStrategy>,
     *   bodyDuplicateStrategyToken?: ?string,
     *   firstName?: ?string,
     *   lastName?: ?string,
     *   listIds?: ?array<string>,
     *   phone?: ?string,
     *   redirectUrl?: ?string,
     *   tagIds?: ?array<string>,
     *   website?: ?string,
     * } $values
     */
    public function __construct(
        array $values,
    ) {
        $this->duplicateStrategy = $values['duplicateStrategy'] ?? null;
        $this->duplicateStrategyToken = $values['duplicateStrategyToken'] ?? null;
        $this->lists = $values['lists'] ?? null;
        $this->tags = $values['tags'] ?? null;
        $this->customAttributes = $values['customAttributes'] ?? null;
        $this->bodyDuplicateStrategy = $values['bodyDuplicateStrategy'] ?? null;
        $this->bodyDuplicateStrategyToken = $values['bodyDuplicateStrategyToken'] ?? null;
        $this->email = $values['email'];
        $this->firstName = $values['firstName'] ?? null;
        $this->lastName = $values['lastName'] ?? null;
        $this->listIds = $values['listIds'] ?? null;
        $this->phone = $values['phone'] ?? null;
        $this->redirectUrl = $values['redirectUrl'] ?? null;
        $this->tagIds = $values['tagIds'] ?? null;
        $this->website = $values['website'] ?? null;
    }
}
